# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 8) do

  create_table "hys_comments", :force => true do |t|
    t.column "hys_thread_id", :integer
    t.column "created_at", :datetime
    t.column "bbcid", :integer, :limit => 9
    t.column "updated_at", :datetime
    t.column "text", :text
    t.column "author", :string, :limit => 128
    t.column "censored", :integer, :limit => 4, :default => 1
    t.column "modified_at", :datetime
    t.column "votes", :integer, :default => 0
  end

  add_index "hys_comments", ["hys_thread_id"], :name => "hys_thread_id_key"
  add_index "hys_comments", ["bbcid"], :name => "bbcid_key"
  add_index "hys_comments", ["votes"], :name => "hys_comments_votes_index"
  add_index "hys_comments", ["text"], :name => "text"

  create_table "hys_threads", :force => true do |t|
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
    t.column "bbcid", :integer, :limit => 9
    t.column "title", :string, :default => "", :null => false
    t.column "rsssize", :integer
  end

  add_index "hys_threads", ["bbcid"], :name => "bbcid_key"

  create_table "news_article_versions", :force => true do |t|
    t.column "news_article_id", :integer
    t.column "title", :string, :limit => 200
    t.column "url", :string, :limit => 250
    t.column "created_at", :datetime
    t.column "version", :integer
    t.column "text", :text
    t.column "text_hash", :string, :limit => 32
  end

  add_index "news_article_versions", ["news_article_id"], :name => "news_article_versions_news_article_id_index"
  add_index "news_article_versions", ["text_hash"], :name => "news_article_versions_text_hash_index"
  add_index "news_article_versions", ["text"], :name => "text"
  add_index "news_article_versions", ["title"], :name => "title"

  create_table "news_articles", :force => true do |t|
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
    t.column "source", :string, :limit => 32
    t.column "guid", :string, :limit => 200
    t.column "url", :string, :limit => 250
    t.column "title", :string, :limit => 200
    t.column "published_at", :datetime
    t.column "latest_text_hash", :string, :limit => 32
    t.column "versions_count", :integer, :default => 0
  end

  add_index "news_articles", ["guid"], :name => "news_articles_guid_index"
  add_index "news_articles", ["source"], :name => "news_articles_source_index"

  create_table "variables", :force => true do |t|
    t.column "key", :string, :limit => 30
    t.column "value", :string, :limit => 250
  end

  add_index "variables", ["key"], :name => "key_key"

  create_table "votes", :force => true do |t|
    t.column "sessionid", :string, :limit => 32
    t.column "created_at", :datetime
    t.column "class", :string, :limit => 32
    t.column "relation_id", :integer
  end

  add_index "votes", ["sessionid"], :name => "votes_sessionid_index"
  add_index "votes", ["class"], :name => "votes_class_index"
  add_index "votes", ["relation_id"], :name => "votes_relation_id_index"

end
