# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 13) do

  create_table "comments", :force => true do |t|
    t.column "name",     :string,  :limit => 64
    t.column "text",     :text
    t.column "email",    :string,  :limit => 64
    t.column "link_id",  :integer
    t.column "linktype", :string,  :limit => 32
  end

  add_index "comments", ["link_id"], :name => "comments_link_id_index"
  add_index "comments", ["linktype"], :name => "comments_linktype_index"

  create_table "news_article_versions", :force => true do |t|
    t.column "news_article_id", :integer
    t.column "title",           :string,   :limit => 200
    t.column "url",             :string,   :limit => 250
    t.column "created_at",      :datetime
    t.column "version",         :integer
    t.column "text",            :text
    t.column "text_hash",       :string,   :limit => 32
    t.column "comments_count",  :integer,                 :default => 0
    t.column "votes",           :integer,                 :default => 0
  end

  add_index "news_article_versions", ["news_article_id"], :name => "news_article_versions_news_article_id_index"
  add_index "news_article_versions", ["text_hash"], :name => "news_article_versions_text_hash_index"
  add_index "news_article_versions", ["comments_count"], :name => "news_article_versions_comments_count_index"
  add_index "news_article_versions", ["votes"], :name => "news_article_versions_votes_index"

  create_table "news_articles", :force => true do |t|
    t.column "created_at",       :datetime
    t.column "updated_at",       :datetime
    t.column "source",           :string,   :limit => 32
    t.column "guid",             :string,   :limit => 200
    t.column "url",              :string,   :limit => 250
    t.column "title",            :string,   :limit => 200
    t.column "published_at",     :datetime
    t.column "latest_text_hash", :string,   :limit => 32
    t.column "versions_count",   :integer,                 :default => 0
  end

  add_index "news_articles", ["guid"], :name => "news_articles_guid_index"
  add_index "news_articles", ["source"], :name => "news_articles_source_index"

  create_table "variables", :force => true do |t|
    t.column "key",   :string, :limit => 30
    t.column "value", :string, :limit => 250
  end

  add_index "variables", ["key"], :name => "key_key"

  create_table "votes", :force => true do |t|
    t.column "sessionid",   :string,   :limit => 32
    t.column "created_at",  :datetime
    t.column "class",       :string,   :limit => 32
    t.column "relation_id", :integer
  end

  add_index "votes", ["sessionid"], :name => "votes_sessionid_index"
  add_index "votes", ["class"], :name => "votes_class_index"
  add_index "votes", ["relation_id"], :name => "votes_relation_id_index"

end
